# Generated by Django 5.1.5 on 2026-08-20 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('employees', '0001_initial'),
        ('schedules', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Marcacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(verbose_name='fecha y hora')),
                ('tipo_verificacion', models.IntegerField(choices=[(0, 'Clave'), (1, 'Huella digital'), (2, 'Tarjeta'), (15, 'Rostro'), (99, 'Otro')], default=99, verbose_name='tipo de verificacion')),
                ('tipo_marcacion', models.IntegerField(choices=[(0, 'Entrada'), (1, 'Salida'), (2, 'Salida a refrigerio'), (3, 'Retorno de refrigerio'), (255, 'Sin definir')], default=255, verbose_name='tipo de marcacion')),
                ('uid_dispositivo', models.IntegerField(blank=True, help_text='Identificador interno del registro en el equipo.', null=True, verbose_name='UID en el dispositivo')),
                ('origen', models.CharField(choices=[('dispositivo', 'Dispositivo biometrico'), ('manual', 'Registro manual')], default='dispositivo', max_length=20, verbose_name='origen')),
                ('observacion', models.CharField(blank=True, help_text='Sustento obligatorio cuando la marcacion se registra manualmente.', max_length=255, verbose_name='observacion')),
                ('descargado_en', models.DateTimeField(auto_now_add=True, verbose_name='descargado en')),
                ('dispositivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcaciones', to='devices.dispositivo', verbose_name='dispositivo')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marcaciones', to='employees.empleado', verbose_name='empleado')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marcaciones_registradas', to=settings.AUTH_USER_MODEL, verbose_name='registrado por')),
            ],
            options={
                'verbose_name': 'marcacion',
                'verbose_name_plural': 'marcaciones',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['empleado', 'fecha_hora'], name='attendance__emplead_185ed2_idx'), models.Index(fields=['-fecha_hora'], name='attendance__fecha_h_c28f23_idx')],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'fecha_hora', 'dispositivo'), name='marcacion_unica_por_empleado_fecha_dispositivo')],
            },
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('hora_entrada_programada', models.TimeField(blank=True, null=True, verbose_name='entrada programada')),
                ('hora_salida_programada', models.TimeField(blank=True, null=True, verbose_name='salida programada')),
                ('marcacion_entrada', models.DateTimeField(blank=True, null=True, verbose_name='marcacion de entrada')),
                ('marcacion_salida', models.DateTimeField(blank=True, null=True, verbose_name='marcacion de salida')),
                ('total_marcaciones', models.PositiveSmallIntegerField(default=0, verbose_name='total de marcaciones')),
                ('minutos_tardanza', models.PositiveIntegerField(default=0, verbose_name='minutos de tardanza')),
                ('minutos_salida_anticipada', models.PositiveIntegerField(default=0, verbose_name='minutos de salida anticipada')),
                ('minutos_trabajados', models.PositiveIntegerField(default=0, verbose_name='minutos trabajados')),
                ('minutos_programados', models.PositiveIntegerField(default=0, verbose_name='minutos programados')),
                ('estado', models.CharField(choices=[('puntual', 'Puntual'), ('tardanza', 'Tardanza'), ('falta', 'Falta injustificada'), ('falta_justificada', 'Falta justificada'), ('permiso', 'Permiso'), ('vacaciones', 'Vacaciones'), ('descanso', 'Descanso'), ('feriado', 'Feriado'), ('incompleto', 'Asistencia incompleta'), ('sin_turno', 'Sin turno asignado')], default='sin_turno', max_length=20, verbose_name='estado')),
                ('es_descontable', models.BooleanField(default=False, help_text='Marca los dias que se consideran en el reporte de descuentos.', verbose_name='afecta el descuento')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='observacion')),
                ('ajustado_manualmente', models.BooleanField(default=False, help_text='Si esta activo, el recalculo automatico respeta este registro.', verbose_name='ajustado manualmente')),
                ('procesado_en', models.DateTimeField(auto_now=True, verbose_name='procesado en')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('ajustado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_ajustados', to=settings.AUTH_USER_MODEL, verbose_name='ajustado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros_asistencia', to='employees.empleado', verbose_name='empleado')),
                ('horario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_asistencia', to='schedules.horario', verbose_name='horario aplicado')),
                ('permiso', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_asistencia', to='schedules.permiso', verbose_name='permiso aplicado')),
                ('turno', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registros_asistencia', to='schedules.turno', verbose_name='turno aplicado')),
            ],
            options={
                'verbose_name': 'registro de asistencia',
                'verbose_name_plural': 'registros de asistencia',
                'ordering': ['-fecha', 'empleado'],
                'indexes': [models.Index(fields=['fecha', 'estado'], name='attendance__fecha_f9e331_idx'), models.Index(fields=['empleado', '-fecha'], name='attendance__emplead_7f5ca9_idx'), models.Index(fields=['estado', 'es_descontable'], name='attendance__estado_edd30e_idx')],
                'constraints': [models.UniqueConstraint(fields=('empleado', 'fecha'), name='registro_asistencia_unico_por_dia')],
            },
        ),
    ]
