# Generated by Django 5.1.5 on 2026-08-20 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario_email', models.EmailField(blank=True, help_text='Se conserva aunque luego se elimine el usuario.', max_length=254, verbose_name='email del usuario')),
                ('accion', models.CharField(choices=[('crear', 'Crear'), ('actualizar', 'Actualizar'), ('eliminar', 'Eliminar'), ('iniciar_sesion', 'Iniciar sesion'), ('cerrar_sesion', 'Cerrar sesion'), ('sincronizar', 'Sincronizar con dispositivo'), ('generar_reporte', 'Generar reporte'), ('ajuste_manual', 'Ajuste manual de asistencia'), ('aprobar_permiso', 'Aprobar o rechazar permiso')], max_length=30, verbose_name='accion')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo afectado')),
                ('objeto_id', models.CharField(blank=True, max_length=50, verbose_name='ID del objeto')),
                ('descripcion', models.CharField(blank=True, max_length=500, verbose_name='descripcion')),
                ('cambios', models.JSONField(blank=True, help_text='Valores anteriores y nuevos de los campos modificados.', null=True, verbose_name='cambios')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='direccion IP')),
                ('user_agent', models.CharField(blank=True, max_length=300, verbose_name='navegador')),
                ('ruta', models.CharField(blank=True, max_length=255, verbose_name='ruta')),
                ('metodo', models.CharField(blank=True, max_length=10, verbose_name='metodo HTTP')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True, verbose_name='fecha y hora')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acciones_auditoria', to=settings.AUTH_USER_MODEL, verbose_name='usuario')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-fecha_hora'],
                'indexes': [models.Index(fields=['-fecha_hora'], name='audit_regis_fecha_h_045efd_idx'), models.Index(fields=['usuario', '-fecha_hora'], name='audit_regis_usuario_bbb4c4_idx'), models.Index(fields=['modelo', 'objeto_id'], name='audit_regis_modelo_8e6c4f_idx')],
            },
        ),
    ]
