# Generated by Django 5.1.5 on 2026-08-20 04:20

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employees', '0001_initial'),
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DiaLaborableConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('minutos_tolerancia_global', models.PositiveSmallIntegerField(default=0, help_text='Se suma a la tolerancia propia de cada horario.', verbose_name='tolerancia global (minutos)')),
                ('considerar_marcacion_unica_como_falta', models.BooleanField(default=False, help_text='Si esta activo, un dia con una sola marcacion se considera falta. Si no, se registra como asistencia incompleta.', verbose_name='una sola marcacion cuenta como falta')),
                ('valor_minuto_tardanza', models.DecimalField(decimal_places=4, default=0, help_text='Si es 0, el descuento se calcula a partir del sueldo del empleado.', max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='costo del minuto de tardanza')),
            ],
            options={
                'verbose_name': 'configuracion de asistencia',
                'verbose_name_plural': 'configuracion de asistencia',
            },
        ),
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('hora_entrada', models.TimeField(verbose_name='hora de entrada')),
                ('hora_salida', models.TimeField(verbose_name='hora de salida')),
                ('tolerancia_entrada', models.PositiveSmallIntegerField(default=5, help_text='Minutos de gracia antes de considerar tardanza.', verbose_name='tolerancia de entrada (minutos)')),
                ('tolerancia_salida', models.PositiveSmallIntegerField(default=5, help_text='Minutos de gracia antes de considerar salida anticipada.', verbose_name='tolerancia de salida (minutos)')),
                ('tiene_refrigerio', models.BooleanField(default=False, verbose_name='tiene refrigerio')),
                ('hora_inicio_refrigerio', models.TimeField(blank=True, null=True, verbose_name='inicio de refrigerio')),
                ('hora_fin_refrigerio', models.TimeField(blank=True, null=True, verbose_name='fin de refrigerio')),
                ('minutos_falta', models.PositiveSmallIntegerField(default=120, help_text='Si la tardanza supera estos minutos, el dia se marca como falta en lugar de tardanza.', verbose_name='minutos para considerar falta')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'horario',
                'verbose_name_plural': 'horarios',
                'ordering': ['hora_entrada', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True, verbose_name='nombre')),
                ('tipo', models.CharField(choices=[('fijo', 'Fijo'), ('rotativo', 'Rotativo'), ('flexible', 'Flexible')], default='fijo', max_length=20, verbose_name='tipo')),
                ('descripcion', models.CharField(blank=True, max_length=255, verbose_name='descripcion')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
            ],
            options={
                'verbose_name': 'turno',
                'verbose_name_plural': 'turnos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='fecha')),
                ('descripcion', models.CharField(max_length=255, verbose_name='descripcion')),
                ('es_recurrente', models.BooleanField(default=False, help_text='Para feriados de fecha fija como Fiestas Patrias o Navidad.', verbose_name='se repite cada ano')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('sede', models.ForeignKey(blank=True, help_text='Vacio significa que aplica a todas las sedes.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feriados', to='organization.sede', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'feriado',
                'verbose_name_plural': 'feriados',
                'ordering': ['-fecha'],
                'constraints': [models.UniqueConstraint(fields=('fecha', 'sede'), name='feriado_unico_por_fecha_sede')],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('vacaciones', 'Vacaciones'), ('descanso_medico', 'Descanso medico'), ('permiso_personal', 'Permiso personal'), ('licencia', 'Licencia'), ('capacitacion', 'Capacitacion'), ('comision', 'Comision de servicio')], max_length=20, verbose_name='tipo')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(verbose_name='fecha de fin')),
                ('con_goce', models.BooleanField(default=True, help_text='Si es sin goce, los dias se consideran para descuento.', verbose_name='con goce de haber')),
                ('motivo', models.TextField(blank=True, verbose_name='motivo')),
                ('documento', models.FileField(blank=True, null=True, upload_to='permisos/', verbose_name='documento de sustento')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=20, verbose_name='estado')),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True, verbose_name='fecha de aprobacion')),
                ('observacion_aprobacion', models.CharField(blank=True, max_length=255, verbose_name='observacion')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL, verbose_name='aprobado por')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='employees.empleado', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'permiso',
                'verbose_name_plural': 'permisos',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['empleado', 'fecha_inicio', 'fecha_fin'], name='schedules_p_emplead_c6bf86_idx')],
            },
        ),
        migrations.CreateModel(
            name='AsignacionTurno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField(verbose_name='fecha de inicio')),
                ('fecha_fin', models.DateField(blank=True, help_text='Vacio significa vigente.', null=True, verbose_name='fecha de fin')),
                ('observacion', models.CharField(blank=True, max_length=255, verbose_name='observacion')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asignaciones_turno', to='employees.empleado', verbose_name='empleado')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='asignaciones', to='schedules.turno', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'asignacion de turno',
                'verbose_name_plural': 'asignaciones de turno',
                'ordering': ['-fecha_inicio'],
                'indexes': [models.Index(fields=['empleado', 'fecha_inicio', 'fecha_fin'], name='schedules_a_emplead_201195_idx')],
            },
        ),
        migrations.CreateModel(
            name='TurnoDetalle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dia_semana', models.IntegerField(choices=[(0, 'Lunes'), (1, 'Martes'), (2, 'Miercoles'), (3, 'Jueves'), (4, 'Viernes'), (5, 'Sabado'), (6, 'Domingo')], verbose_name='dia de la semana')),
                ('horario', models.ForeignKey(blank=True, help_text='Dejar vacio si el dia es de descanso.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='detalles_turno', to='schedules.horario', verbose_name='horario')),
                ('turno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='schedules.turno', verbose_name='turno')),
            ],
            options={
                'verbose_name': 'detalle de turno',
                'verbose_name_plural': 'detalles de turno',
                'ordering': ['turno', 'dia_semana'],
                'constraints': [models.UniqueConstraint(fields=('turno', 'dia_semana'), name='turno_detalle_unico_por_dia')],
            },
        ),
    ]
