# Generated by Django 5.1.5 on 2026-08-20 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, verbose_name='nombre')),
                ('ip', models.GenericIPAddressField(default='192.168.18.202', protocol='IPv4', verbose_name='direccion IP')),
                ('puerto', models.PositiveIntegerField(default=4370, verbose_name='puerto')),
                ('password_comunicacion', models.IntegerField(default=0, help_text='Clave de comunicacion configurada en el equipo (0 si no tiene).', verbose_name='clave de comunicacion')),
                ('timeout', models.PositiveIntegerField(default=10, verbose_name='timeout en segundos')),
                ('force_udp', models.BooleanField(default=False, help_text='Activar solo si el equipo no responde por TCP.', verbose_name='forzar UDP')),
                ('ubicacion', models.CharField(blank=True, max_length=255, verbose_name='ubicacion fisica')),
                ('modelo', models.CharField(blank=True, max_length=100, verbose_name='modelo')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='numero de serie')),
                ('version_firmware', models.CharField(blank=True, max_length=100, verbose_name='version de firmware')),
                ('version_plataforma', models.CharField(blank=True, max_length=100, verbose_name='plataforma')),
                ('version_rostro', models.CharField(blank=True, max_length=50, verbose_name='version del algoritmo facial')),
                ('version_huella', models.CharField(blank=True, max_length=50, verbose_name='version del algoritmo de huella')),
                ('mac', models.CharField(blank=True, max_length=50, verbose_name='direccion MAC')),
                ('admin_user_id', models.CharField(default='6999383', help_text='Este usuario nunca se elimina durante una sincronizacion.', max_length=20, verbose_name='ID del administrador del equipo')),
                ('estado', models.CharField(choices=[('conectado', 'Conectado'), ('desconectado', 'Desconectado'), ('error', 'Error de conexion'), ('desconocido', 'Desconocido')], default='desconocido', max_length=20, verbose_name='estado')),
                ('ultima_conexion', models.DateTimeField(blank=True, null=True, verbose_name='ultima conexion exitosa')),
                ('ultima_sincronizacion_marcaciones', models.DateTimeField(blank=True, help_text='Marca desde cuando se descargan las marcaciones nuevas.', null=True, verbose_name='ultima descarga de marcaciones')),
                ('activo', models.BooleanField(default=True, verbose_name='activo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('sede', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispositivos', to='organization.sede', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'dispositivo biometrico',
                'verbose_name_plural': 'dispositivos biometricos',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='RegistroSincronizacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operacion', models.CharField(choices=[('probar_conexion', 'Probar conexion'), ('subir_empleados', 'Subir empleados al equipo'), ('descargar_empleados', 'Descargar empleados del equipo'), ('descargar_huellas', 'Respaldar huellas'), ('restaurar_huellas', 'Restaurar huellas en el equipo'), ('descargar_marcaciones', 'Descargar marcaciones'), ('eliminar_empleado', 'Eliminar empleado del equipo'), ('sincronizar_hora', 'Sincronizar hora del equipo'), ('limpiar_marcaciones', 'Limpiar marcaciones del equipo')], max_length=30, verbose_name='operacion')),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('exitoso', 'Exitoso'), ('fallido', 'Fallido'), ('parcial', 'Parcial')], default='en_proceso', max_length=20, verbose_name='estado')),
                ('registros_procesados', models.IntegerField(default=0, verbose_name='registros procesados')),
                ('registros_nuevos', models.IntegerField(default=0, verbose_name='registros nuevos')),
                ('registros_fallidos', models.IntegerField(default=0, verbose_name='registros fallidos')),
                ('mensaje', models.TextField(blank=True, verbose_name='mensaje')),
                ('detalle', models.JSONField(blank=True, null=True, verbose_name='detalle')),
                ('inicio', models.DateTimeField(auto_now_add=True, verbose_name='inicio')),
                ('fin', models.DateTimeField(blank=True, null=True, verbose_name='fin')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sincronizaciones', to='devices.dispositivo', verbose_name='dispositivo')),
                ('ejecutado_por', models.ForeignKey(blank=True, help_text='Nulo cuando la ejecuta una tarea programada.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sincronizaciones', to=settings.AUTH_USER_MODEL, verbose_name='ejecutado por')),
            ],
            options={
                'verbose_name': 'registro de sincronizacion',
                'verbose_name_plural': 'registros de sincronizacion',
                'ordering': ['-inicio'],
            },
        ),
        migrations.AddConstraint(
            model_name='dispositivo',
            constraint=models.UniqueConstraint(fields=('ip', 'puerto'), name='dispositivo_ip_puerto_unico'),
        ),
        migrations.AddIndex(
            model_name='registrosincronizacion',
            index=models.Index(fields=['-inicio'], name='devices_reg_inicio_edc245_idx'),
        ),
        migrations.AddIndex(
            model_name='registrosincronizacion',
            index=models.Index(fields=['dispositivo', 'operacion'], name='devices_reg_disposi_90885b_idx'),
        ),
    ]
