# Generated by Django 5.1.5 on 2026-08-20 05:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
        ('employees', '0002_empleado_uid_dispositivo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dispositivo',
            name='adms_habilitado',
            field=models.BooleanField(default=False, help_text='Permite que este equipo envie datos a los endpoints /iclock/. Los datos solo se aceptan si el numero de serie coincide.', verbose_name='aceptar conexiones ADMS'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='adms_ip_permitida',
            field=models.GenericIPAddressField(blank=True, help_text='Si se indica, solo se aceptan peticiones ADMS que provengan de esta IP. Es la principal defensa contra marcaciones falsas desde la red.', null=True, protocol='IPv4', verbose_name='IP autorizada para ADMS'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='adms_op_stamp',
            field=models.CharField(default='0', max_length=32, verbose_name='marca de tiempo de operaciones'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='adms_stamp',
            field=models.CharField(default='0', help_text='Contador que el equipo usa para saber desde donde reenviar las marcaciones.', max_length=32, verbose_name='marca de tiempo de marcaciones'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='modo',
            field=models.CharField(choices=[('sdk', 'SDK (el servidor consulta al equipo por el puerto 4370)'), ('adms', 'ADMS / Push (el equipo envia los datos al servidor)')], default='sdk', max_length=10, verbose_name='modo de comunicacion'),
        ),
        migrations.AddField(
            model_name='dispositivo',
            name='ultima_conexion_adms',
            field=models.DateTimeField(blank=True, null=True, verbose_name='ultima conexion ADMS'),
        ),
        migrations.CreateModel(
            name='ComandoDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('actualizar_usuario', 'Actualizar usuario'), ('eliminar_usuario', 'Eliminar usuario'), ('actualizar_huella', 'Restaurar huella'), ('solicitar_datos', 'Solicitar reenvio de datos'), ('solicitar_info', 'Solicitar informacion del equipo'), ('limpiar_marcaciones', 'Limpiar marcaciones del equipo'), ('reiniciar', 'Reiniciar el equipo')], max_length=30, verbose_name='tipo')),
                ('comando', models.TextField(help_text='Instruccion en el formato que espera el equipo, sin el prefijo C:<id>:', verbose_name='comando')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de entrega'), ('enviado', 'Entregado al equipo'), ('confirmado', 'Ejecutado correctamente'), ('fallido', 'El equipo reporto un error')], default='pendiente', max_length=20, verbose_name='estado')),
                ('codigo_retorno', models.IntegerField(blank=True, help_text='Lo reporta el equipo al ejecutar el comando. 0 significa exito.', null=True, verbose_name='codigo de retorno')),
                ('respuesta', models.CharField(blank=True, max_length=255, verbose_name='respuesta del equipo')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('enviado_en', models.DateTimeField(blank=True, null=True, verbose_name='entregado en')),
                ('confirmado_en', models.DateTimeField(blank=True, null=True, verbose_name='confirmado en')),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandos_creados', to=settings.AUTH_USER_MODEL, verbose_name='creado por')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comandos', to='devices.dispositivo', verbose_name='dispositivo')),
                ('empleado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comandos_dispositivo', to='employees.empleado', verbose_name='empleado relacionado')),
            ],
            options={
                'verbose_name': 'comando de dispositivo',
                'verbose_name_plural': 'comandos de dispositivo',
                'ordering': ['creado_en'],
                'indexes': [models.Index(fields=['dispositivo', 'estado'], name='devices_com_disposi_31f1fa_idx'), models.Index(fields=['-creado_en'], name='devices_com_creado__ea454f_idx')],
            },
        ),
        migrations.CreateModel(
            name='PeticionADMS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, verbose_name='numero de serie recibido')),
                ('ruta', models.CharField(max_length=255, verbose_name='ruta')),
                ('metodo', models.CharField(max_length=10, verbose_name='metodo HTTP')),
                ('parametros', models.JSONField(blank=True, null=True, verbose_name='parametros de la URL')),
                ('cuerpo', models.TextField(blank=True, verbose_name='cuerpo de la peticion')),
                ('respuesta', models.TextField(blank=True, verbose_name='respuesta enviada')),
                ('ip_origen', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP de origen')),
                ('aceptada', models.BooleanField(default=True, help_text='Falso si se rechazo por numero de serie o IP no autorizados.', verbose_name='aceptada')),
                ('registros_procesados', models.IntegerField(default=0, verbose_name='registros procesados')),
                ('recibida_en', models.DateTimeField(auto_now_add=True, verbose_name='recibida en')),
                ('dispositivo', models.ForeignKey(blank=True, help_text='Nulo si el numero de serie no corresponde a ningun equipo registrado.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peticiones_adms', to='devices.dispositivo', verbose_name='dispositivo')),
            ],
            options={
                'verbose_name': 'peticion ADMS',
                'verbose_name_plural': 'peticiones ADMS',
                'ordering': ['-recibida_en'],
                'indexes': [models.Index(fields=['-recibida_en'], name='devices_pet_recibid_45324a_idx'), models.Index(fields=['dispositivo', '-recibida_en'], name='devices_pet_disposi_42861e_idx')],
            },
        ),
    ]
