# Generated by Django 5.1.5 on 2026-08-20 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_dispositivo_adms_habilitado_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioDispositivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(max_length=20, verbose_name='PIN reportado por el equipo')),
                ('nombre', models.CharField(blank=True, max_length=100, verbose_name='nombre en el equipo')),
                ('privilegio', models.IntegerField(default=0, verbose_name='privilegio')),
                ('tarjeta', models.CharField(blank=True, max_length=30, verbose_name='tarjeta')),
                ('grupo', models.CharField(blank=True, max_length=20, verbose_name='grupo')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('dispositivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuarios_reportados', to='devices.dispositivo', verbose_name='dispositivo')),
            ],
            options={
                'verbose_name': 'usuario reportado por el equipo',
                'verbose_name_plural': 'usuarios reportados por el equipo',
                'ordering': ['codigo_empleado'],
                'constraints': [models.UniqueConstraint(fields=('dispositivo', 'codigo_empleado'), name='usuario_dispositivo_unico')],
            },
        ),
    ]
