# Generated by Django 5.1.5 on 2026-08-20 04:20

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('devices', '0001_initial'),
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_empleado', models.CharField(help_text='Identificador numerico usado en el dispositivo biometrico (user_id).', max_length=20, unique=True, validators=[django.core.validators.RegexValidator('^\\d+$', 'El codigo debe ser numerico.')], verbose_name='codigo de empleado')),
                ('dni', models.CharField(max_length=15, unique=True, verbose_name='DNI')),
                ('nombres', models.CharField(max_length=100, verbose_name='nombres')),
                ('apellido_paterno', models.CharField(max_length=60, verbose_name='apellido paterno')),
                ('apellido_materno', models.CharField(blank=True, max_length=60, verbose_name='apellido materno')),
                ('fecha_nacimiento', models.DateField(blank=True, null=True, verbose_name='fecha de nacimiento')),
                ('sexo', models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1, verbose_name='sexo')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='empleados/fotos/', verbose_name='foto')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='correo electronico')),
                ('telefono', models.CharField(blank=True, max_length=20, verbose_name='telefono')),
                ('direccion', models.CharField(blank=True, max_length=255, verbose_name='direccion')),
                ('fecha_ingreso', models.DateField(verbose_name='fecha de ingreso')),
                ('fecha_cese', models.DateField(blank=True, null=True, verbose_name='fecha de cese')),
                ('tipo_contrato', models.CharField(choices=[('indefinido', 'Plazo indeterminado'), ('plazo_fijo', 'Plazo fijo'), ('practicas', 'Practicas'), ('locacion', 'Locacion de servicios')], default='indefinido', max_length=20, verbose_name='tipo de contrato')),
                ('estado', models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo'), ('cesado', 'Cesado'), ('vacaciones', 'De vacaciones')], default='activo', max_length=20, verbose_name='estado')),
                ('sueldo_basico', models.DecimalField(blank=True, decimal_places=2, help_text='Se usa para calcular el monto de los descuentos por tardanza o falta.', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='sueldo basico')),
                ('tiene_huella', models.BooleanField(default=False, verbose_name='tiene huella enrolada')),
                ('cantidad_huellas', models.PositiveSmallIntegerField(default=0, verbose_name='cantidad de huellas')),
                ('tiene_rostro', models.BooleanField(default=False, verbose_name='tiene rostro enrolado')),
                ('tiene_tarjeta', models.BooleanField(default=False, verbose_name='tiene tarjeta')),
                ('numero_tarjeta', models.CharField(blank=True, max_length=20, verbose_name='numero de tarjeta')),
                ('privilegio_dispositivo', models.IntegerField(choices=[(0, 'Usuario'), (2, 'Registrador'), (14, 'Administrador del equipo')], default=0, verbose_name='privilegio en el dispositivo')),
                ('password_dispositivo', models.CharField(blank=True, help_text='Clave numerica para marcar por teclado en el equipo.', max_length=20, verbose_name='clave del dispositivo')),
                ('sincronizado_dispositivo', models.BooleanField(default=False, verbose_name='sincronizado')),
                ('fecha_ultima_sincronizacion', models.DateTimeField(blank=True, null=True, verbose_name='ultima sincronizacion')),
                ('creado_en', models.DateTimeField(auto_now_add=True, verbose_name='creado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organization.area', verbose_name='area')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organization.cargo', verbose_name='cargo')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organization.departamento', verbose_name='departamento')),
                ('sede', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='empleados', to='organization.sede', verbose_name='sede')),
            ],
            options={
                'verbose_name': 'empleado',
                'verbose_name_plural': 'empleados',
                'ordering': ['apellido_paterno', 'apellido_materno', 'nombres'],
            },
        ),
        migrations.CreateModel(
            name='HuellaEmpleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finger_id', models.PositiveSmallIntegerField(help_text='Indice del dedo segun el dispositivo (0 a 9).', verbose_name='dedo')),
                ('template', models.TextField(help_text='Plantilla biometrica codificada en base64.', verbose_name='plantilla')),
                ('size', models.PositiveIntegerField(default=0, verbose_name='tamano en bytes')),
                ('valid', models.PositiveSmallIntegerField(default=1, verbose_name='validez')),
                ('capturado_en', models.DateTimeField(auto_now_add=True, verbose_name='capturado en')),
                ('actualizado_en', models.DateTimeField(auto_now=True, verbose_name='actualizado en')),
                ('dispositivo_origen', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='huellas_respaldadas', to='devices.dispositivo', verbose_name='dispositivo de origen')),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='huellas', to='employees.empleado', verbose_name='empleado')),
            ],
            options={
                'verbose_name': 'huella de empleado',
                'verbose_name_plural': 'huellas de empleados',
                'ordering': ['empleado', 'finger_id'],
            },
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['codigo_empleado'], name='employees_e_codigo__29852b_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estado'], name='employees_e_estado_af4575_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['sede', 'departamento'], name='employees_e_sede_id_b57c59_idx'),
        ),
        migrations.AddConstraint(
            model_name='huellaempleado',
            constraint=models.UniqueConstraint(fields=('empleado', 'finger_id'), name='huella_unica_por_dedo'),
        ),
    ]
