# Generated by Django 5.1.5 on 2026-08-20 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='uid_dispositivo',
            field=models.PositiveIntegerField(blank=True, help_text='Indice interno que asigna el equipo (1 a 65535). Es distinto del codigo de empleado y se conserva para no duplicar al re-sincronizar.', null=True, verbose_name='UID en el dispositivo'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='privilegio_dispositivo',
            field=models.IntegerField(choices=[(0, 'Usuario'), (14, 'Administrador del equipo')], default=0, verbose_name='privilegio en el dispositivo'),
        ),
    ]
