# Generated by Django 5.1.5 on 2026-08-20 04:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReporteGenerado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('tardanzas', 'Reporte de tardanzas'), ('faltas', 'Reporte de faltas'), ('descuentos', 'Reporte de descuentos'), ('marcaciones', 'Reporte de marcaciones'), ('horas_trabajadas', 'Reporte de horas trabajadas'), ('asistencia_general', 'Reporte general de asistencia')], max_length=30, verbose_name='tipo')),
                ('formato', models.CharField(choices=[('excel', 'Excel'), ('pdf', 'PDF')], default='excel', max_length=10, verbose_name='formato')),
                ('fecha_inicio', models.DateField(verbose_name='desde')),
                ('fecha_fin', models.DateField(verbose_name='hasta')),
                ('filtros', models.JSONField(blank=True, help_text='Sede, departamento, empleados y demas criterios usados.', null=True, verbose_name='filtros aplicados')),
                ('archivo', models.FileField(upload_to='reportes/%Y/%m/', verbose_name='archivo')),
                ('total_registros', models.IntegerField(default=0, verbose_name='total de registros')),
                ('generado_en', models.DateTimeField(auto_now_add=True, verbose_name='generado en')),
                ('generado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reportes_generados', to=settings.AUTH_USER_MODEL, verbose_name='generado por')),
            ],
            options={
                'verbose_name': 'reporte generado',
                'verbose_name_plural': 'reportes generados',
                'ordering': ['-generado_en'],
                'indexes': [models.Index(fields=['-generado_en'], name='reports_rep_generad_af7119_idx'), models.Index(fields=['tipo'], name='reports_rep_tipo_054f16_idx')],
            },
        ),
    ]
